#!/bin/sh
# Copyright 2017 Nick Clifford, GPLv3

selftest()
{
	# NOT ACTUALLY REAL KEYS
	local aws_secret_access_key="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" # NOT REAL
	local aws_access_key_id="AKIAIOSFODNN7EXAMPLE" # NOT REAL
	local aws_service="s3"
	local aws_region="us-east-1"
	local aws_timestamp="20150915T124500Z"
	local aws_date="20150915"

	local uri="/"
	local host="my-precious-bucket.s3.amazonaws.com"
	
	local payload_hash auth_header test_key verify_header

	payload_hash=$(printf "" | sha256)
	
	auth_header=$(make_authorization_header "GET" \
		"$host" \
		"$uri" "" "" \
		"$aws_region" "$aws_service" "$payload_hash")

	test_key=$(make_signing_key "$aws_region" "$aws_service")
	if [ "$test_key" != "7b0b3063e375aa1e25890e0cae1c674785b8d8709cd2bf11ec670b96587650da" ]; then
		echo "Test signing key failed"
		echo "Expected 7b0b3063e375aa1e25890e0cae1c674785b8d8709cd2bf11ec670b96587650da"
		echo "Got $test_key"
	fi


	verify_header="Authorization: AWS4-HMAC-SHA256 Credential=AKIAIOSFODNN7EXAMPLE/20150915/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=182072eb53d85c36b2d791a1fa46a12d23454ec1e921b02075c23aee40166d5a"


	if [ "$auth_header" != "$verify_header" ]; then
		echo "Final test failed. Auth header didn't match"
		echo "We had: $auth_header"
		echo "We wanted: $verify_header"
	fi

	echo "Done"

}


